/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CambiaPanel;
import FiveCodMover.FiveCodMoverJFrame;
import necesario.FadeEffect;
import vista.Alertas.Cerrar;
import vista.Alertas.warnningCerrar;


/**
 *
 * @author Kevin
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
        setLocationRelativeTo(null);
        CambiaPanel cambiaPanel = new CambiaPanel(PanelPrincipal, new Inicio());
        FadeEffect.fadeInFrame(this, 50, 0.1f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roboto1 = new rojeru_san.efectos.Roboto();
        pnlMenu = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnReportes = new rojerusan.RSButtonHover();
        btnProyecto = new rojerusan.RSButtonHover();
        btnConsumo = new rojerusan.RSButtonHover();
        btnInventario = new rojerusan.RSButtonHover();
        btnCompras = new rojerusan.RSButtonHover();
        btnProveedores = new rojerusan.RSButtonHover();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnMenu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PanelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(600, 926));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(33, 45, 62));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/icons8_male_user_110px.png"))); // NOI18N
        pnlMenu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 111));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");
        pnlMenu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 170, 26));

        btnReportes.setBackground(new java.awt.Color(33, 45, 62));
        btnReportes.setBorder(null);
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/icons8_bar_chart_30px.png"))); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setColorHover(new java.awt.Color(64, 68, 81));
        btnReportes.setFocusPainted(false);
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportesMouseClicked(evt);
            }
        });
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        pnlMenu.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 170, -1));

        btnProyecto.setBackground(new java.awt.Color(33, 45, 62));
        btnProyecto.setBorder(null);
        btnProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/icons8_paste_30px_1.png"))); // NOI18N
        btnProyecto.setText("Proyecto");
        btnProyecto.setColorHover(new java.awt.Color(64, 68, 81));
        btnProyecto.setFocusPainted(false);
        btnProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProyectoMouseClicked(evt);
            }
        });
        btnProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProyectoActionPerformed(evt);
            }
        });
        pnlMenu.add(btnProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 170, -1));

        btnConsumo.setBackground(new java.awt.Color(33, 45, 62));
        btnConsumo.setBorder(null);
        btnConsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/icons8_graph_30px_1.png"))); // NOI18N
        btnConsumo.setText("Consumo");
        btnConsumo.setColorHover(new java.awt.Color(64, 68, 81));
        btnConsumo.setFocusPainted(false);
        btnConsumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsumoMouseClicked(evt);
            }
        });
        btnConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsumoActionPerformed(evt);
            }
        });
        pnlMenu.add(btnConsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 170, -1));

        btnInventario.setBackground(new java.awt.Color(33, 45, 62));
        btnInventario.setBorder(null);
        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/icons8_empty_box_30px.png"))); // NOI18N
        btnInventario.setText("Inventario");
        btnInventario.setColorHover(new java.awt.Color(64, 68, 81));
        btnInventario.setFocusPainted(false);
        btnInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInventarioMouseClicked(evt);
            }
        });
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        pnlMenu.add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 170, -1));

        btnCompras.setBackground(new java.awt.Color(33, 45, 62));
        btnCompras.setBorder(null);
        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/icons8_shopping_cart_30px.png"))); // NOI18N
        btnCompras.setText("Compras");
        btnCompras.setColorHover(new java.awt.Color(64, 68, 81));
        btnCompras.setFocusPainted(false);
        btnCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComprasMouseClicked(evt);
            }
        });
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });
        pnlMenu.add(btnCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 170, -1));

        btnProveedores.setBackground(new java.awt.Color(33, 45, 62));
        btnProveedores.setBorder(null);
        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/icons8_user_groups_30px.png"))); // NOI18N
        btnProveedores.setText("Proveedores");
        btnProveedores.setColorHover(new java.awt.Color(64, 68, 81));
        btnProveedores.setFocusPainted(false);
        btnProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProveedoresMouseClicked(evt);
            }
        });
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        pnlMenu.add(btnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/icons8_logout_rounded_left_50px_1.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        pnlMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 50, 70));

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 600));

        jPanel2.setBackground(new java.awt.Color(65, 165, 238));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/icons8_menu_50px_1.png"))); // NOI18N
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuMouseClicked(evt);
            }
        });
        jPanel2.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 48));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/color-helper.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 30, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/icons8_delete_35px_4.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 860, 54));

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrincipal.setLayout(new javax.swing.BoxLayout(PanelPrincipal, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 860, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
         FiveCodMoverJFrame.MousePressed(evt);
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        FiveCodMoverJFrame.MouseDraggedFrame(evt, this);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseClicked
        
        if(btnReportes.isFocusable()){
            btnReportes.setBackground(new java.awt.Color(65,165,238));
            btnProyecto.setBackground(new java.awt.Color(33,45,62));
            btnConsumo.setBackground(new java.awt.Color(33,45,62));
            btnInventario.setBackground(new java.awt.Color(33,45,62));
            btnCompras.setBackground(new java.awt.Color(33,45,62));
            btnProveedores.setBackground(new java.awt.Color(33,45,62));
            
        }
         CambiaPanel cambiaPanel = new CambiaPanel(PanelPrincipal, new PnlReporte());
    }//GEN-LAST:event_btnReportesMouseClicked

    private void btnProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProyectoMouseClicked
       if(btnProyecto.isFocusable()){
            btnProyecto.setBackground(new java.awt.Color(65,165,238));
            btnReportes.setBackground(new java.awt.Color(33,45,62));
            btnConsumo.setBackground(new java.awt.Color(33,45,62));
            btnInventario.setBackground(new java.awt.Color(33,45,62));
            btnCompras.setBackground(new java.awt.Color(33,45,62));
            btnProveedores.setBackground(new java.awt.Color(33,45,62));
            
        }
        CambiaPanel cambiaPanel = new CambiaPanel(PanelPrincipal, new PnlProyecto());
    }//GEN-LAST:event_btnProyectoMouseClicked

    private void btnProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProyectoActionPerformed

    private void btnConsumoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsumoMouseClicked
       if(btnConsumo.isFocusable()){
            btnConsumo.setBackground(new java.awt.Color(65,165,238));
            btnReportes.setBackground(new java.awt.Color(33,45,62));
            btnProyecto.setBackground(new java.awt.Color(33,45,62));
            btnInventario.setBackground(new java.awt.Color(33,45,62));
            btnCompras.setBackground(new java.awt.Color(33,45,62));
            btnProveedores.setBackground(new java.awt.Color(33,45,62));
            
        }
       CambiaPanel cambiaPanel = new CambiaPanel(PanelPrincipal, new PnlConsumo());
    }//GEN-LAST:event_btnConsumoMouseClicked

    private void btnConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsumoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsumoActionPerformed

    private void btnInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventarioMouseClicked
      if(btnInventario.isFocusable()){
            btnInventario.setBackground(new java.awt.Color(65,165,238));
            btnReportes.setBackground(new java.awt.Color(33,45,62));
            btnConsumo.setBackground(new java.awt.Color(33,45,62));
            btnProyecto.setBackground(new java.awt.Color(33,45,62));
            btnCompras.setBackground(new java.awt.Color(33,45,62));
            btnProveedores.setBackground(new java.awt.Color(33,45,62));
            
        }
       CambiaPanel cambiaPanel = new CambiaPanel(PanelPrincipal, new PInventario());
    }//GEN-LAST:event_btnInventarioMouseClicked

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprasMouseClicked
        if(btnCompras.isFocusable()){
            btnCompras.setBackground(new java.awt.Color(65,165,238));
            btnReportes.setBackground(new java.awt.Color(33,45,62));
            btnConsumo.setBackground(new java.awt.Color(33,45,62));
            btnInventario.setBackground(new java.awt.Color(33,45,62));
            btnProyecto.setBackground(new java.awt.Color(33,45,62));
            btnProveedores.setBackground(new java.awt.Color(33,45,62));
            
        }
         CambiaPanel cambiaPanel = new CambiaPanel(PanelPrincipal, new PnlCompras());
    }//GEN-LAST:event_btnComprasMouseClicked

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprasActionPerformed

    private void btnProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedoresMouseClicked
        if(btnProveedores.isFocusable()){
            btnProveedores.setBackground(new java.awt.Color(65,165,238));
            btnReportes.setBackground(new java.awt.Color(33,45,62));
            btnConsumo.setBackground(new java.awt.Color(33,45,62));
            btnInventario.setBackground(new java.awt.Color(33,45,62));
            btnCompras.setBackground(new java.awt.Color(33,45,62));
            btnProyecto.setBackground(new java.awt.Color(33,45,62));
            
        }
         CambiaPanel cambiaPanel = new CambiaPanel(PanelPrincipal, new PnlProveedores());
    }//GEN-LAST:event_btnProveedoresMouseClicked

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        Cerrar c = new Cerrar(this, true);
        c.titulo.setText("¿ESTAS SEGURO?");
        c.msj.setText("SE CERRARA LA APLICACIÓN");
        c.msj1.setText("");
        c.setVisible(true);
        
        
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setExtendedState(DashBoard.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        warnningCerrar wa = new warnningCerrar(this, true);
        wa.titulo.setText("¿ESTAS SEGURO?");
        wa.msj.setText("SE CERRARA LA SESIÓN ACTUAL");
        wa.msj1.setText("");
        wa.setVisible(true);
        
       if (warnningCerrar.salir) {
            this.dispose();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseClicked
      
      
    }//GEN-LAST:event_btnMenuMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public transient javax.swing.JPanel PanelPrincipal;
    private rojerusan.RSButtonHover btnCompras;
    private rojerusan.RSButtonHover btnConsumo;
    private rojerusan.RSButtonHover btnInventario;
    private javax.swing.JLabel btnMenu;
    private rojerusan.RSButtonHover btnProveedores;
    private rojerusan.RSButtonHover btnProyecto;
    private rojerusan.RSButtonHover btnReportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlMenu;
    private rojeru_san.efectos.Roboto roboto1;
    // End of variables declaration//GEN-END:variables
}
