/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;



import controlador.Conexion;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import vista.Alertas.Cerrar;
import vista.Alertas.Succes;
import vista.Alertas.errror;


/**
 *
 * @author Kevin
 */
public class PnlProyecto extends javax.swing.JPanel {

    /**
     * Creates new form PnlProyecto
     */
    public PnlProyecto() {
        initComponents();
        erNombre.setVisible(false);
        erBodega.setVisible(false);
        erDirec.setVisible(false);
        
        cargarTabla();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbpro = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtdireccion = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtbodega = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        fechaIni = new rojeru_san.rsdate.RSDateChooser();
        fechafin = new rojeru_san.rsdate.RSDateChooser();
        erBodega = new javax.swing.JLabel();
        erNombre = new javax.swing.JLabel();
        erDirec = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(860, 550));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbpro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "N-bodega", "Nombre", "Direccion", "F-Inicio", "F-Finl"
            }
        ));
        jScrollPane2.setViewportView(tbpro);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 536, 330));

        jPanel2.setBackground(new java.awt.Color(65, 165, 238));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PROYECTOS");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/icons8_paste_30px_1.png"))); // NOI18N

        txtBuscar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(51, 51, 51));
        txtBuscar.setText("BUSCAR");
        txtBuscar.setBorder(null);
        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarMouseClicked(evt);
            }
        });
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/icons8_search_30px_2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 392, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(3, 3, 3)))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 12, 810, -1));

        jButton2.setBackground(new java.awt.Color(65, 165, 238));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/icons8_delete_trash_20px.png"))); // NOI18N
        jButton2.setText("ELIMINAR");
        jButton2.setBorder(null);
        jButton2.setFocusPainted(false);
        jButton2.setMaximumSize(new java.awt.Dimension(79, 20));
        jButton2.setMinimumSize(new java.awt.Dimension(79, 20));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 129, 34));

        jButton1.setBackground(new java.awt.Color(65, 165, 238));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/icons8_edit_20px.png"))); // NOI18N
        jButton1.setText("EDITAR");
        jButton1.setBorder(null);
        jButton1.setFocusPainted(false);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 129, 33));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Agregar nuevo proyecto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, -1));

        jButton3.setBackground(new java.awt.Color(65, 165, 238));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/icons8_project_20px.png"))); // NOI18N
        jButton3.setText("NUEVO PROYECTO");
        jButton3.setBorder(null);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 186, 33));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtdireccion.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtdireccion.setBorder(null);
        txtdireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdireccionMouseClicked(evt);
            }
        });
        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdireccionKeyTyped(evt);
            }
        });
        jPanel3.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 130, 30));

        txtnombre.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtnombre.setBorder(null);
        txtnombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnombreMouseClicked(evt);
            }
        });
        txtnombre.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtnombreCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        jPanel3.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 130, 30));

        txtbodega.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtbodega.setBorder(null);
        txtbodega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbodegaMouseClicked(evt);
            }
        });
        txtbodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbodegaActionPerformed(evt);
            }
        });
        txtbodega.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbodegaKeyTyped(evt);
            }
        });
        jPanel3.add(txtbodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 130, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Nombre");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Direccion");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Fecha inicio");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Fecha fin");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(65, 165, 238));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 130, 10));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("N-bodega");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(65, 165, 238));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 130, -1));

        jSeparator3.setBackground(new java.awt.Color(65, 165, 238));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 130, 10));

        fechaIni.setColorBackground(new java.awt.Color(65, 165, 238));
        fechaIni.setColorForeground(new java.awt.Color(0, 0, 0));
        fechaIni.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        fechaIni.setFormatoFecha("dd/MM/yyyy");
        fechaIni.setFuente(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fechaIni.setPlaceholder("Seleccionar Fecha");
        fechaIni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fechaIniMouseClicked(evt);
            }
        });
        jPanel3.add(fechaIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 160, -1));

        fechafin.setColorBackground(new java.awt.Color(65, 165, 238));
        fechafin.setColorForeground(new java.awt.Color(0, 0, 0));
        fechafin.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        fechafin.setFormatoFecha("dd/MM/yyyy");
        fechafin.setFuente(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        fechafin.setPlaceholder("Seleccionar Fecha");
        fechafin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fechafinMouseClicked(evt);
            }
        });
        jPanel3.add(fechafin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 160, -1));

        erBodega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/icons8_high_priority_20px.png"))); // NOI18N
        jPanel3.add(erBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 20, 30));

        erNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/icons8_high_priority_20px.png"))); // NOI18N
        jPanel3.add(erNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 20, 30));

        erDirec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/iconos/icons8_high_priority_20px.png"))); // NOI18N
        jPanel3.add(erDirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 20, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 260, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMouseClicked
        if(txtBuscar.isFocusable()){
            txtBuscar.setText("");
        }
        else{
            txtBuscar.setText("BUSCAR");
        }
    }//GEN-LAST:event_txtBuscarMouseClicked

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed

        DefaultTableModel modeloTabla = (DefaultTableModel) tbpro.getModel();
        modeloTabla.setRowCount(0);
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        int[] ancho = {5, 5, 20, 20, 20, 20};
        for (int i = 0; i < tbpro.getColumnCount(); i++) {
            tbpro.getColumnModel().getColumn(i).setPreferredWidth(ancho[i]);
        }
        try {
            int id = Integer.parseInt(txtBuscar.getText());
            Connection con;
            con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT idproyec,Nbodega,nombre,direccion,fechaInicio,fechaFin FROM proyec WHERE idProyec=?");
            ps.setInt(1, id);
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while (rs.next()) {
                Object[] fila = new Object[columnas];
                for (int indice = 0; indice < columnas; indice++) {
                    fila[indice] = rs.getObject(indice + 1);
                }
                modeloTabla.addRow(fila);

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());

        }

        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        
            String Nombre = txtnombre.getText();
        

            
            String direccion = txtdireccion.getText();
        
  try {
            if(txtnombre.getText().isEmpty()){
                erNombre.setVisible(true);
                txtnombre.requestFocus();
                
            }
            if(txtbodega.getText().isEmpty()){
                erBodega.setVisible(true);
                txtbodega.requestFocus();
            }
            if(txtdireccion.getText().isEmpty()){
                erDirec.setVisible(true);
                txtdireccion.requestFocus();
            }
            if(txtnombre.getText().isEmpty() || txtbodega.getText().isEmpty() || txtdireccion.getText().isEmpty() || fechaIni.getDatoFecha() == null || fechafin.getDatoFecha() == null){
                errror r = new errror(new DashBoard(), true);
                r.titulo.setText("OOPS...");
                r.msj.setText("Te hacen falta campos por llenar");
                r.msj1.setText("");
                r.setVisible(true);
                txtnombre.requestFocus();
            }
            else{
//                Cerrar c = new Cerrar();
//                c.titulo.setText("OOPS...");
//                c.msj.setText("Te hacen falta campos por llenar");
//                c.msj1.setText("");
//                c.setVisible(true);
//                  JOptionPane.showMessageDialog(null, "Campos vacios");
//                    erNombre.setVisible(true);
             int bodega = Integer.parseInt(txtbodega.getText());
             
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("INSERT INTO proyec (Nbodega,nombre,direccion,fechaInicio,fechaFin) VALUES (?,?,?,?,?)");
            ps.setInt(1, bodega);
            ps.setString(2, Nombre);
            ps.setString(3, direccion);
            ps.setDate(4, new java.sql.Date(fechaIni.getDatoFecha().getYear(),fechaIni.getDatoFecha().getMonth(),fechaIni.getDatoFecha().getDay()));
            ps.setDate(5, new java.sql.Date(fechafin.getDatoFecha().getYear(),fechafin.getDatoFecha().getMonth(),fechafin.getDatoFecha().getDay()));
     
           

            ps.executeUpdate();
            ///JOptionPane.showMessageDialog(null, "Registro guardado");
            Succes s = new Succes(new DashBoard(), true );
            s.titulo.setText("Éxito");
            s.msj.setText("Proyecto agregado");
            s.msj1.setText("");
            s.setVisible(true);
            

            //limpiar();
                txtnombre.setText("");
                txtbodega.setText("");
                txtdireccion.setText("");
                fechaIni.setPlaceholder("Selecionar Fecha");
                fechafin.setPlaceholder("Selecionar Fecha");
                
            cargarTabla();
                    
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    
        
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
                PreparedStatement ps;
        ResultSet rs;

        try {
            int fila = tbpro.getSelectedRow();
            int id = Integer.parseInt(tbpro.getValueAt(fila, 0).toString());

            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("DELETE FROM proyec WHERE idProyec=?");
            ps.setInt(1, id);
            ps.executeUpdate();

            cargarTabla();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());

        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtbodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbodegaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbodegaActionPerformed

    private void txtnombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombreMouseClicked
        erNombre.setVisible(false);
    }//GEN-LAST:event_txtnombreMouseClicked

    private void txtbodegaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbodegaMouseClicked
        erBodega.setVisible(false);
    }//GEN-LAST:event_txtbodegaMouseClicked

    private void txtdireccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdireccionMouseClicked
        erDirec.setVisible(false);
    }//GEN-LAST:event_txtdireccionMouseClicked

    private void txtnombreCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtnombreCaretPositionChanged
       
    }//GEN-LAST:event_txtnombreCaretPositionChanged

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        
            erNombre.setVisible(false);
        
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtbodegaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbodegaKeyTyped
         erBodega.setVisible(false);
    }//GEN-LAST:event_txtbodegaKeyTyped

    private void txtdireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyTyped
        erDirec.setVisible(false);
    }//GEN-LAST:event_txtdireccionKeyTyped

    private void fechaIniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaIniMouseClicked
        
    }//GEN-LAST:event_fechaIniMouseClicked

    private void fechafinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechafinMouseClicked
       
    }//GEN-LAST:event_fechafinMouseClicked

        private void cargarTabla()  {

        DefaultTableModel modeloTabla = (DefaultTableModel) tbpro.getModel();
        modeloTabla.setRowCount(0);
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        String name="";
        int[] ancho = {5, 5, 20, 20, 20, 20};
        for (int i = 0; i < tbpro.getColumnCount(); i++) {
            tbpro.getColumnModel().getColumn(i).setPreferredWidth(ancho[i]);
        }
        try {
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT idproyec,Nbodega,nombre,direccion,fechaInicio,fechaFin FROM proyec");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while (rs.next()) {
                Object[] fila = new Object[columnas];
                for (int indice = 0; indice < columnas; indice++) {
                    fila[indice] = rs.getObject(indice + 1);
  
                }
                modeloTabla.addRow(fila);

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());

        }

    }
    
    
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel erBodega;
    private javax.swing.JLabel erDirec;
    private javax.swing.JLabel erNombre;
    private rojeru_san.rsdate.RSDateChooser fechaIni;
    private rojeru_san.rsdate.RSDateChooser fechafin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tbpro;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtbodega;
    private javax.swing.JTextField txtdireccion;
    public javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
